// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Netlify.OpenApiClient.Sites.Item.Dev_servers.Item.State
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum StatePostRequestBody_state
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "starting")]
        #pragma warning disable CS1591
        Starting,
        #pragma warning restore CS1591
        [EnumMember(Value = "live")]
        #pragma warning disable CS1591
        Live,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "done")]
        #pragma warning disable CS1591
        Done,
        #pragma warning restore CS1591
    }
}
