// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Netlify.OpenApiClient.Models;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Branch.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Branch
{
    /// <summary>
    /// Builds and executes requests for operations under \sites\{site_id}\database\branch
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BranchRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Netlify.OpenApiClient.sites.item.database.branch.item collection</summary>
        /// <param name="position">The branch ID</param>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Branch.Item.WithBranch_ItemRequestBuilder"/></returns>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Branch.Item.WithBranch_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("branch_id", position);
                return new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Branch.Item.WithBranch_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Branch.BranchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BranchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{site_id}/database/branch", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Branch.BranchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BranchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{site_id}/database/branch", rawUrl)
        {
        }
        /// <summary>
        /// Creates a new database branch. If a branch already exists for the specified branch ID, returns the existing connection string.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Models.DatabaseBranchResponse"/></returns>
        /// <param name="body">Request body for creating a database branch</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Netlify.OpenApiClient.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Netlify.OpenApiClient.Models.DatabaseBranchResponse?> PostAsync(global::Soenneker.Netlify.OpenApiClient.Models.CreateDatabaseBranchRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Netlify.OpenApiClient.Models.DatabaseBranchResponse> PostAsync(global::Soenneker.Netlify.OpenApiClient.Models.CreateDatabaseBranchRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Netlify.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Netlify.OpenApiClient.Models.DatabaseBranchResponse>(requestInfo, global::Soenneker.Netlify.OpenApiClient.Models.DatabaseBranchResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new database branch. If a branch already exists for the specified branch ID, returns the existing connection string.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request body for creating a database branch</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Netlify.OpenApiClient.Models.CreateDatabaseBranchRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Netlify.OpenApiClient.Models.CreateDatabaseBranchRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Branch.BranchRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Branch.BranchRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Branch.BranchRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
