// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Compute.Settings;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Compute
{
    /// <summary>
    /// Builds and executes requests for operations under \sites\{site_id}\database\compute
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ComputeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The settings property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Compute.Settings.SettingsRequestBuilder Settings
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Compute.Settings.SettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Compute.ComputeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ComputeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{site_id}/database/compute", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Compute.ComputeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ComputeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{site_id}/database/compute", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
