// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Netlify.OpenApiClient.Agent_runners.Item.Sessions
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetStateQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "live")]
        #pragma warning disable CS1591
        Live,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
    }
}
