// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Netlify.OpenApiClient.Models;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Ssl.Certificates;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Netlify.OpenApiClient.Sites.Item.Ssl
{
    /// <summary>
    /// Builds and executes requests for operations under \sites\{site_id}\ssl
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SslRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The certificates property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Ssl.Certificates.CertificatesRequestBuilder Certificates
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Ssl.Certificates.CertificatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Sites.Item.Ssl.SslRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SslRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{site_id}/ssl{?ca_certificates*,certificate*,key*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Sites.Item.Ssl.SslRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SslRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{site_id}/ssl{?ca_certificates*,certificate*,key*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Models.SniCertificate"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Netlify.OpenApiClient.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Netlify.OpenApiClient.Models.SniCertificate?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Netlify.OpenApiClient.Models.SniCertificate> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Netlify.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Netlify.OpenApiClient.Models.SniCertificate>(requestInfo, global::Soenneker.Netlify.OpenApiClient.Models.SniCertificate.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Provisions or updates a TLS certificate for the site.**Creating a certificate (site has no certificate):**- Omit certificate params to initiate Let&apos;s Encrypt provisioning- Provide certificate, key, and ca_certificates to upload a custom certificate**Updating a certificate (site already has a certificate):**- REQUIRES certificate, key, and ca_certificates to replace with a new custom certificate- Use POST /api/v1/sites/{site_id}/ssl/renew to renew an existing Let&apos;s Encrypt certificate
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Models.SniCertificate"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Netlify.OpenApiClient.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Netlify.OpenApiClient.Models.SniCertificate?> PostAsync(Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Sites.Item.Ssl.SslRequestBuilder.SslRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Netlify.OpenApiClient.Models.SniCertificate> PostAsync(Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Sites.Item.Ssl.SslRequestBuilder.SslRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Netlify.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Netlify.OpenApiClient.Models.SniCertificate>(requestInfo, global::Soenneker.Netlify.OpenApiClient.Models.SniCertificate.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Provisions or updates a TLS certificate for the site.**Creating a certificate (site has no certificate):**- Omit certificate params to initiate Let&apos;s Encrypt provisioning- Provide certificate, key, and ca_certificates to upload a custom certificate**Updating a certificate (site already has a certificate):**- REQUIRES certificate, key, and ca_certificates to replace with a new custom certificate- Use POST /api/v1/sites/{site_id}/ssl/renew to renew an existing Let&apos;s Encrypt certificate
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Sites.Item.Ssl.SslRequestBuilder.SslRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Sites.Item.Ssl.SslRequestBuilder.SslRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Sites.Item.Ssl.SslRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Ssl.SslRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Ssl.SslRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Provisions or updates a TLS certificate for the site.**Creating a certificate (site has no certificate):**- Omit certificate params to initiate Let&apos;s Encrypt provisioning- Provide certificate, key, and ca_certificates to upload a custom certificate**Updating a certificate (site already has a certificate):**- REQUIRES certificate, key, and ca_certificates to replace with a new custom certificate- Use POST /api/v1/sites/{site_id}/ssl/renew to renew an existing Let&apos;s Encrypt certificate
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SslRequestBuilderPostQueryParameters 
        {
            /// <summary>PEM-encoded CA certificate chain. Required when updating an existing certificate.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("ca_certificates")]
            public string? CaCertificates { get; set; }
#nullable restore
#else
            [QueryParameter("ca_certificates")]
            public string CaCertificates { get; set; }
#endif
            /// <summary>PEM-encoded certificate. Required when updating an existing certificate.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("certificate")]
            public string? Certificate { get; set; }
#nullable restore
#else
            [QueryParameter("certificate")]
            public string Certificate { get; set; }
#endif
            /// <summary>PEM-encoded private key. Required when updating an existing certificate.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("key")]
            public string? Key { get; set; }
#nullable restore
#else
            [QueryParameter("key")]
            public string Key { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
