// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Netlify.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AccountSetup_period
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "monthly")]
        #pragma warning disable CS1591
        Monthly,
        #pragma warning restore CS1591
        [EnumMember(Value = "yearly")]
        #pragma warning disable CS1591
        Yearly,
        #pragma warning restore CS1591
    }
}
