// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Netlify.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AgentRunnerSession : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The agent_config property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerSessionConfig? AgentConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerSessionConfig AgentConfig { get; set; }
#endif
        /// <summary>The agent_runner_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AgentRunnerId { get; set; }
#nullable restore
#else
        public string AgentRunnerId { get; set; }
#endif
        /// <summary>The attached_file_keys property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AttachedFileKeys { get; set; }
#nullable restore
#else
        public List<string> AttachedFileKeys { get; set; }
#endif
        /// <summary>The commit_sha property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommitSha { get; set; }
#nullable restore
#else
        public string CommitSha { get; set; }
#endif
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The deploy_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeployId { get; set; }
#nullable restore
#else
        public string DeployId { get; set; }
#endif
        /// <summary>The deploy_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeployUrl { get; set; }
#nullable restore
#else
        public string DeployUrl { get; set; }
#endif
        /// <summary>The dev_server_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DevServerId { get; set; }
#nullable restore
#else
        public string DevServerId { get; set; }
#endif
        /// <summary>The done_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DoneAt { get; set; }
#nullable restore
#else
        public string DoneAt { get; set; }
#endif
        /// <summary>The duration property</summary>
        public int? Duration { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The is_published property</summary>
        public bool? IsPublished { get; set; }
        /// <summary>The prompt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prompt { get; set; }
#nullable restore
#else
        public string Prompt { get; set; }
#endif
        /// <summary>The result property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Result { get; set; }
#nullable restore
#else
        public string Result { get; set; }
#endif
        /// <summary>The result_diff property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResultDiff { get; set; }
#nullable restore
#else
        public string ResultDiff { get; set; }
#endif
        /// <summary>The result_zip_file_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResultZipFileName { get; set; }
#nullable restore
#else
        public string ResultZipFileName { get; set; }
#endif
        /// <summary>The state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The steps property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerSessionStep>? Steps { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerSessionStep> Steps { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The updated_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerUser? User { get; set; }
#nullable restore
#else
        public global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerUser User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerSession"/> and sets the default values.
        /// </summary>
        public AgentRunnerSession()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerSession"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerSession CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerSession();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agent_config", n => { AgentConfig = n.GetObjectValue<global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerSessionConfig>(global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerSessionConfig.CreateFromDiscriminatorValue); } },
                { "agent_runner_id", n => { AgentRunnerId = n.GetStringValue(); } },
                { "attached_file_keys", n => { AttachedFileKeys = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "commit_sha", n => { CommitSha = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "deploy_id", n => { DeployId = n.GetStringValue(); } },
                { "deploy_url", n => { DeployUrl = n.GetStringValue(); } },
                { "dev_server_id", n => { DevServerId = n.GetStringValue(); } },
                { "done_at", n => { DoneAt = n.GetStringValue(); } },
                { "duration", n => { Duration = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_published", n => { IsPublished = n.GetBoolValue(); } },
                { "prompt", n => { Prompt = n.GetStringValue(); } },
                { "result", n => { Result = n.GetStringValue(); } },
                { "result_diff", n => { ResultDiff = n.GetStringValue(); } },
                { "result_zip_file_name", n => { ResultZipFileName = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "steps", n => { Steps = n.GetCollectionOfObjectValues<global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerSessionStep>(global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerSessionStep.CreateFromDiscriminatorValue)?.AsList(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerUser>(global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerUser.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerSessionConfig>("agent_config", AgentConfig);
            writer.WriteStringValue("agent_runner_id", AgentRunnerId);
            writer.WriteCollectionOfPrimitiveValues<string>("attached_file_keys", AttachedFileKeys);
            writer.WriteStringValue("commit_sha", CommitSha);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("deploy_id", DeployId);
            writer.WriteStringValue("deploy_url", DeployUrl);
            writer.WriteStringValue("dev_server_id", DevServerId);
            writer.WriteStringValue("done_at", DoneAt);
            writer.WriteIntValue("duration", Duration);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_published", IsPublished);
            writer.WriteStringValue("prompt", Prompt);
            writer.WriteStringValue("result", Result);
            writer.WriteStringValue("result_diff", ResultDiff);
            writer.WriteStringValue("result_zip_file_name", ResultZipFileName);
            writer.WriteStringValue("state", State);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerSessionStep>("steps", Steps);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteObjectValue<global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerUser>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
