// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Netlify.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AgentRunner : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active_session_created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActiveSessionCreatedAt { get; set; }
#nullable restore
#else
        public string ActiveSessionCreatedAt { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attached_file_keys property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AttachedFileKeys { get; set; }
#nullable restore
#else
        public List<string> AttachedFileKeys { get; set; }
#endif
        /// <summary>The base_deploy_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BaseDeployId { get; set; }
#nullable restore
#else
        public string BaseDeployId { get; set; }
#endif
        /// <summary>The branch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Branch { get; set; }
#nullable restore
#else
        public string Branch { get; set; }
#endif
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The current_task property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrentTask { get; set; }
#nullable restore
#else
        public string CurrentTask { get; set; }
#endif
        /// <summary>The done_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DoneAt { get; set; }
#nullable restore
#else
        public string DoneAt { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The latest_session_deploy_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LatestSessionDeployId { get; set; }
#nullable restore
#else
        public string LatestSessionDeployId { get; set; }
#endif
        /// <summary>The latest_session_deploy_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LatestSessionDeployUrl { get; set; }
#nullable restore
#else
        public string LatestSessionDeployUrl { get; set; }
#endif
        /// <summary>The merge_commit_error property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MergeCommitError { get; set; }
#nullable restore
#else
        public string MergeCommitError { get; set; }
#endif
        /// <summary>The merge_commit_is_being_created property</summary>
        public bool? MergeCommitIsBeingCreated { get; set; }
        /// <summary>The merge_commit_sha property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MergeCommitSha { get; set; }
#nullable restore
#else
        public string MergeCommitSha { get; set; }
#endif
        /// <summary>The parent_agent_runner_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentAgentRunnerId { get; set; }
#nullable restore
#else
        public string ParentAgentRunnerId { get; set; }
#endif
        /// <summary>The pr_branch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrBranch { get; set; }
#nullable restore
#else
        public string PrBranch { get; set; }
#endif
        /// <summary>The pr_error property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrError { get; set; }
#nullable restore
#else
        public string PrError { get; set; }
#endif
        /// <summary>The pr_is_being_created property</summary>
        public bool? PrIsBeingCreated { get; set; }
        /// <summary>The pr_number property</summary>
        public int? PrNumber { get; set; }
        /// <summary>The pr_state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrState { get; set; }
#nullable restore
#else
        public string PrState { get; set; }
#endif
        /// <summary>The pr_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrUrl { get; set; }
#nullable restore
#else
        public string PrUrl { get; set; }
#endif
        /// <summary>The result_branch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResultBranch { get; set; }
#nullable restore
#else
        public string ResultBranch { get; set; }
#endif
        /// <summary>The result_diff property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResultDiff { get; set; }
#nullable restore
#else
        public string ResultDiff { get; set; }
#endif
        /// <summary>The sha property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sha { get; set; }
#nullable restore
#else
        public string Sha { get; set; }
#endif
        /// <summary>The site_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SiteId { get; set; }
#nullable restore
#else
        public string SiteId { get; set; }
#endif
        /// <summary>The state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The updated_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerUser? User { get; set; }
#nullable restore
#else
        public global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerUser User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Models.AgentRunner"/> and sets the default values.
        /// </summary>
        public AgentRunner()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Models.AgentRunner"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Netlify.OpenApiClient.Models.AgentRunner CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Netlify.OpenApiClient.Models.AgentRunner();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active_session_created_at", n => { ActiveSessionCreatedAt = n.GetStringValue(); } },
                { "attached_file_keys", n => { AttachedFileKeys = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "base_deploy_id", n => { BaseDeployId = n.GetStringValue(); } },
                { "branch", n => { Branch = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "current_task", n => { CurrentTask = n.GetStringValue(); } },
                { "done_at", n => { DoneAt = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "latest_session_deploy_id", n => { LatestSessionDeployId = n.GetStringValue(); } },
                { "latest_session_deploy_url", n => { LatestSessionDeployUrl = n.GetStringValue(); } },
                { "merge_commit_error", n => { MergeCommitError = n.GetStringValue(); } },
                { "merge_commit_is_being_created", n => { MergeCommitIsBeingCreated = n.GetBoolValue(); } },
                { "merge_commit_sha", n => { MergeCommitSha = n.GetStringValue(); } },
                { "parent_agent_runner_id", n => { ParentAgentRunnerId = n.GetStringValue(); } },
                { "pr_branch", n => { PrBranch = n.GetStringValue(); } },
                { "pr_error", n => { PrError = n.GetStringValue(); } },
                { "pr_is_being_created", n => { PrIsBeingCreated = n.GetBoolValue(); } },
                { "pr_number", n => { PrNumber = n.GetIntValue(); } },
                { "pr_state", n => { PrState = n.GetStringValue(); } },
                { "pr_url", n => { PrUrl = n.GetStringValue(); } },
                { "result_branch", n => { ResultBranch = n.GetStringValue(); } },
                { "result_diff", n => { ResultDiff = n.GetStringValue(); } },
                { "sha", n => { Sha = n.GetStringValue(); } },
                { "site_id", n => { SiteId = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerUser>(global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerUser.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("active_session_created_at", ActiveSessionCreatedAt);
            writer.WriteCollectionOfPrimitiveValues<string>("attached_file_keys", AttachedFileKeys);
            writer.WriteStringValue("base_deploy_id", BaseDeployId);
            writer.WriteStringValue("branch", Branch);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("current_task", CurrentTask);
            writer.WriteStringValue("done_at", DoneAt);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("latest_session_deploy_id", LatestSessionDeployId);
            writer.WriteStringValue("latest_session_deploy_url", LatestSessionDeployUrl);
            writer.WriteStringValue("merge_commit_error", MergeCommitError);
            writer.WriteBoolValue("merge_commit_is_being_created", MergeCommitIsBeingCreated);
            writer.WriteStringValue("merge_commit_sha", MergeCommitSha);
            writer.WriteStringValue("parent_agent_runner_id", ParentAgentRunnerId);
            writer.WriteStringValue("pr_branch", PrBranch);
            writer.WriteStringValue("pr_error", PrError);
            writer.WriteBoolValue("pr_is_being_created", PrIsBeingCreated);
            writer.WriteIntValue("pr_number", PrNumber);
            writer.WriteStringValue("pr_state", PrState);
            writer.WriteStringValue("pr_url", PrUrl);
            writer.WriteStringValue("result_branch", ResultBranch);
            writer.WriteStringValue("result_diff", ResultDiff);
            writer.WriteStringValue("sha", Sha);
            writer.WriteStringValue("site_id", SiteId);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteObjectValue<global::Soenneker.Netlify.OpenApiClient.Models.AgentRunnerUser>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
