// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Netlify.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BuildStatus : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active property</summary>
        public int? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The build_count property</summary>
        public int? BuildCount { get; set; }
        /// <summary>The enqueued property</summary>
        public int? Enqueued { get; set; }
        /// <summary>The minutes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Netlify.OpenApiClient.Models.BuildStatus_minutes? Minutes { get; set; }
#nullable restore
#else
        public global::Soenneker.Netlify.OpenApiClient.Models.BuildStatus_minutes Minutes { get; set; }
#endif
        /// <summary>The pending_concurrency property</summary>
        public int? PendingConcurrency { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Models.BuildStatus"/> and sets the default values.
        /// </summary>
        public BuildStatus()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Models.BuildStatus"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Netlify.OpenApiClient.Models.BuildStatus CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Netlify.OpenApiClient.Models.BuildStatus();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetIntValue(); } },
                { "build_count", n => { BuildCount = n.GetIntValue(); } },
                { "enqueued", n => { Enqueued = n.GetIntValue(); } },
                { "minutes", n => { Minutes = n.GetObjectValue<global::Soenneker.Netlify.OpenApiClient.Models.BuildStatus_minutes>(global::Soenneker.Netlify.OpenApiClient.Models.BuildStatus_minutes.CreateFromDiscriminatorValue); } },
                { "pending_concurrency", n => { PendingConcurrency = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("active", Active);
            writer.WriteIntValue("build_count", BuildCount);
            writer.WriteIntValue("enqueued", Enqueued);
            writer.WriteObjectValue<global::Soenneker.Netlify.OpenApiClient.Models.BuildStatus_minutes>("minutes", Minutes);
            writer.WriteIntValue("pending_concurrency", PendingConcurrency);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
