// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Netlify.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BuildStatus_minutes : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The current property</summary>
        public int? Current { get; set; }
        /// <summary>The current_average_sec property</summary>
        public int? CurrentAverageSec { get; set; }
        /// <summary>The included_minutes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IncludedMinutes { get; set; }
#nullable restore
#else
        public string IncludedMinutes { get; set; }
#endif
        /// <summary>The included_minutes_with_packs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IncludedMinutesWithPacks { get; set; }
#nullable restore
#else
        public string IncludedMinutesWithPacks { get; set; }
#endif
        /// <summary>The last_updated_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastUpdatedAt { get; set; }
#nullable restore
#else
        public string LastUpdatedAt { get; set; }
#endif
        /// <summary>The period_end_date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PeriodEndDate { get; set; }
#nullable restore
#else
        public string PeriodEndDate { get; set; }
#endif
        /// <summary>The period_start_date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PeriodStartDate { get; set; }
#nullable restore
#else
        public string PeriodStartDate { get; set; }
#endif
        /// <summary>The previous property</summary>
        public int? Previous { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Models.BuildStatus_minutes"/> and sets the default values.
        /// </summary>
        public BuildStatus_minutes()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Models.BuildStatus_minutes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Netlify.OpenApiClient.Models.BuildStatus_minutes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Netlify.OpenApiClient.Models.BuildStatus_minutes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "current", n => { Current = n.GetIntValue(); } },
                { "current_average_sec", n => { CurrentAverageSec = n.GetIntValue(); } },
                { "included_minutes", n => { IncludedMinutes = n.GetStringValue(); } },
                { "included_minutes_with_packs", n => { IncludedMinutesWithPacks = n.GetStringValue(); } },
                { "last_updated_at", n => { LastUpdatedAt = n.GetStringValue(); } },
                { "period_end_date", n => { PeriodEndDate = n.GetStringValue(); } },
                { "period_start_date", n => { PeriodStartDate = n.GetStringValue(); } },
                { "previous", n => { Previous = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("current", Current);
            writer.WriteIntValue("current_average_sec", CurrentAverageSec);
            writer.WriteStringValue("included_minutes", IncludedMinutes);
            writer.WriteStringValue("included_minutes_with_packs", IncludedMinutesWithPacks);
            writer.WriteStringValue("last_updated_at", LastUpdatedAt);
            writer.WriteStringValue("period_end_date", PeriodEndDate);
            writer.WriteStringValue("period_start_date", PeriodStartDate);
            writer.WriteIntValue("previous", Previous);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
