// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Netlify.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BuildLogMsg_section
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "initializing")]
        #pragma warning disable CS1591
        Initializing,
        #pragma warning restore CS1591
        [EnumMember(Value = "building")]
        #pragma warning disable CS1591
        Building,
        #pragma warning restore CS1591
        [EnumMember(Value = "deploying")]
        #pragma warning disable CS1591
        Deploying,
        #pragma warning restore CS1591
        [EnumMember(Value = "cleanup")]
        #pragma warning disable CS1591
        Cleanup,
        #pragma warning restore CS1591
        [EnumMember(Value = "postprocessing")]
        #pragma warning disable CS1591
        Postprocessing,
        #pragma warning restore CS1591
    }
}
