// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Netlify.OpenApiClient.Models
{
    /// <summary>
    /// Compute endpoint status for a branch
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DatabaseBranchCompute : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Maximum compute units for autoscaling</summary>
        public double? AutoscalingLimitMaxCu { get; set; }
        /// <summary>Minimum compute units for autoscaling</summary>
        public double? AutoscalingLimitMinCu { get; set; }
        /// <summary>The current state of the compute endpoint</summary>
        public global::Soenneker.Netlify.OpenApiClient.Models.DatabaseBranchCompute_current_state? CurrentState { get; set; }
        /// <summary>When the compute endpoint was last active</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastActive { get; set; }
#nullable restore
#else
        public string LastActive { get; set; }
#endif
        /// <summary>Seconds of inactivity before the compute endpoint is suspended</summary>
        public long? SuspendTimeoutSeconds { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Models.DatabaseBranchCompute"/> and sets the default values.
        /// </summary>
        public DatabaseBranchCompute()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Models.DatabaseBranchCompute"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Netlify.OpenApiClient.Models.DatabaseBranchCompute CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Netlify.OpenApiClient.Models.DatabaseBranchCompute();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoscaling_limit_max_cu", n => { AutoscalingLimitMaxCu = n.GetDoubleValue(); } },
                { "autoscaling_limit_min_cu", n => { AutoscalingLimitMinCu = n.GetDoubleValue(); } },
                { "current_state", n => { CurrentState = n.GetEnumValue<global::Soenneker.Netlify.OpenApiClient.Models.DatabaseBranchCompute_current_state>(); } },
                { "last_active", n => { LastActive = n.GetStringValue(); } },
                { "suspend_timeout_seconds", n => { SuspendTimeoutSeconds = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("autoscaling_limit_max_cu", AutoscalingLimitMaxCu);
            writer.WriteDoubleValue("autoscaling_limit_min_cu", AutoscalingLimitMinCu);
            writer.WriteEnumValue<global::Soenneker.Netlify.OpenApiClient.Models.DatabaseBranchCompute_current_state>("current_state", CurrentState);
            writer.WriteStringValue("last_active", LastActive);
            writer.WriteLongValue("suspend_timeout_seconds", SuspendTimeoutSeconds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
