// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Netlify.OpenApiClient.Models
{
    /// <summary>The current state of the branch</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DatabaseBranchDetail_state
    {
        [EnumMember(Value = "init")]
        #pragma warning disable CS1591
        Init,
        #pragma warning restore CS1591
        [EnumMember(Value = "creating")]
        #pragma warning disable CS1591
        Creating,
        #pragma warning restore CS1591
        [EnumMember(Value = "resetting")]
        #pragma warning disable CS1591
        Resetting,
        #pragma warning restore CS1591
        [EnumMember(Value = "ready")]
        #pragma warning disable CS1591
        Ready,
        #pragma warning restore CS1591
        [EnumMember(Value = "archived")]
        #pragma warning disable CS1591
        Archived,
        #pragma warning restore CS1591
    }
}
