// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Netlify.OpenApiClient.Models
{
    /// <summary>
    /// Request body for setting compute settings. All fields are optional; only provided fields are updated.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DatabaseComputeSettingsRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Maximum compute units (0.25 to 16.0). Must be greater than or equal to min_cu. max_cu - min_cu must not exceed 8.0.</summary>
        public double? MaxCu { get; set; }
        /// <summary>Minimum compute units (0.25 to 16.0). Must be less than or equal to max_cu.</summary>
        public double? MinCu { get; set; }
        /// <summary>Seconds of inactivity before the compute endpoint is suspended. Use -1 for always on, or a non-negative value.</summary>
        public long? SleepTimeoutSeconds { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Models.DatabaseComputeSettingsRequest"/> and sets the default values.
        /// </summary>
        public DatabaseComputeSettingsRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Models.DatabaseComputeSettingsRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Netlify.OpenApiClient.Models.DatabaseComputeSettingsRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Netlify.OpenApiClient.Models.DatabaseComputeSettingsRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "max_cu", n => { MaxCu = n.GetDoubleValue(); } },
                { "min_cu", n => { MinCu = n.GetDoubleValue(); } },
                { "sleep_timeout_seconds", n => { SleepTimeoutSeconds = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("max_cu", MaxCu);
            writer.WriteDoubleValue("min_cu", MinCu);
            writer.WriteLongValue("sleep_timeout_seconds", SleepTimeoutSeconds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
