// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Netlify.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Deploy : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The admin_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdminUrl { get; set; }
#nullable restore
#else
        public string AdminUrl { get; set; }
#endif
        /// <summary>The branch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Branch { get; set; }
#nullable restore
#else
        public string Branch { get; set; }
#endif
        /// <summary>The build_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BuildId { get; set; }
#nullable restore
#else
        public string BuildId { get; set; }
#endif
        /// <summary>The commit_ref property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommitRef { get; set; }
#nullable restore
#else
        public string CommitRef { get; set; }
#endif
        /// <summary>The commit_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommitUrl { get; set; }
#nullable restore
#else
        public string CommitUrl { get; set; }
#endif
        /// <summary>The context property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Context { get; set; }
#nullable restore
#else
        public string Context { get; set; }
#endif
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The deploy_ssl_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeploySslUrl { get; set; }
#nullable restore
#else
        public string DeploySslUrl { get; set; }
#endif
        /// <summary>The deploy_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeployUrl { get; set; }
#nullable restore
#else
        public string DeployUrl { get; set; }
#endif
        /// <summary>The draft property</summary>
        public bool? Draft { get; set; }
        /// <summary>The error_message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorMessage { get; set; }
#nullable restore
#else
        public string ErrorMessage { get; set; }
#endif
        /// <summary>The framework property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Framework { get; set; }
#nullable restore
#else
        public string Framework { get; set; }
#endif
        /// <summary>The function_schedules property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Netlify.OpenApiClient.Models.FunctionSchedule>? FunctionSchedules { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Netlify.OpenApiClient.Models.FunctionSchedule> FunctionSchedules { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The locked property</summary>
        public bool? Locked { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The published_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublishedAt { get; set; }
#nullable restore
#else
        public string PublishedAt { get; set; }
#endif
        /// <summary>The required property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Required { get; set; }
#nullable restore
#else
        public List<string> Required { get; set; }
#endif
        /// <summary>The required_functions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RequiredFunctions { get; set; }
#nullable restore
#else
        public List<string> RequiredFunctions { get; set; }
#endif
        /// <summary>The review_id property</summary>
        public double? ReviewId { get; set; }
        /// <summary>The review_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReviewUrl { get; set; }
#nullable restore
#else
        public string ReviewUrl { get; set; }
#endif
        /// <summary>The screenshot_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScreenshotUrl { get; set; }
#nullable restore
#else
        public string ScreenshotUrl { get; set; }
#endif
        /// <summary>The site_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SiteId { get; set; }
#nullable restore
#else
        public string SiteId { get; set; }
#endif
        /// <summary>The skew_protection_token property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SkewProtectionToken { get; set; }
#nullable restore
#else
        public string SkewProtectionToken { get; set; }
#endif
        /// <summary>The skipped property</summary>
        public bool? Skipped { get; set; }
        /// <summary>The ssl_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SslUrl { get; set; }
#nullable restore
#else
        public string SslUrl { get; set; }
#endif
        /// <summary>The state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The updated_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Models.Deploy"/> and sets the default values.
        /// </summary>
        public Deploy()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Models.Deploy"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Netlify.OpenApiClient.Models.Deploy CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Netlify.OpenApiClient.Models.Deploy();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "admin_url", n => { AdminUrl = n.GetStringValue(); } },
                { "branch", n => { Branch = n.GetStringValue(); } },
                { "build_id", n => { BuildId = n.GetStringValue(); } },
                { "commit_ref", n => { CommitRef = n.GetStringValue(); } },
                { "commit_url", n => { CommitUrl = n.GetStringValue(); } },
                { "context", n => { Context = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "deploy_ssl_url", n => { DeploySslUrl = n.GetStringValue(); } },
                { "deploy_url", n => { DeployUrl = n.GetStringValue(); } },
                { "draft", n => { Draft = n.GetBoolValue(); } },
                { "error_message", n => { ErrorMessage = n.GetStringValue(); } },
                { "framework", n => { Framework = n.GetStringValue(); } },
                { "function_schedules", n => { FunctionSchedules = n.GetCollectionOfObjectValues<global::Soenneker.Netlify.OpenApiClient.Models.FunctionSchedule>(global::Soenneker.Netlify.OpenApiClient.Models.FunctionSchedule.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "locked", n => { Locked = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "published_at", n => { PublishedAt = n.GetStringValue(); } },
                { "required", n => { Required = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "required_functions", n => { RequiredFunctions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "review_id", n => { ReviewId = n.GetDoubleValue(); } },
                { "review_url", n => { ReviewUrl = n.GetStringValue(); } },
                { "screenshot_url", n => { ScreenshotUrl = n.GetStringValue(); } },
                { "site_id", n => { SiteId = n.GetStringValue(); } },
                { "skew_protection_token", n => { SkewProtectionToken = n.GetStringValue(); } },
                { "skipped", n => { Skipped = n.GetBoolValue(); } },
                { "ssl_url", n => { SslUrl = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("admin_url", AdminUrl);
            writer.WriteStringValue("branch", Branch);
            writer.WriteStringValue("build_id", BuildId);
            writer.WriteStringValue("commit_ref", CommitRef);
            writer.WriteStringValue("commit_url", CommitUrl);
            writer.WriteStringValue("context", Context);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("deploy_ssl_url", DeploySslUrl);
            writer.WriteStringValue("deploy_url", DeployUrl);
            writer.WriteBoolValue("draft", Draft);
            writer.WriteStringValue("error_message", ErrorMessage);
            writer.WriteStringValue("framework", Framework);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Netlify.OpenApiClient.Models.FunctionSchedule>("function_schedules", FunctionSchedules);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("locked", Locked);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("published_at", PublishedAt);
            writer.WriteCollectionOfPrimitiveValues<string>("required", Required);
            writer.WriteCollectionOfPrimitiveValues<string>("required_functions", RequiredFunctions);
            writer.WriteDoubleValue("review_id", ReviewId);
            writer.WriteStringValue("review_url", ReviewUrl);
            writer.WriteStringValue("screenshot_url", ScreenshotUrl);
            writer.WriteStringValue("site_id", SiteId);
            writer.WriteStringValue("skew_protection_token", SkewProtectionToken);
            writer.WriteBoolValue("skipped", Skipped);
            writer.WriteStringValue("ssl_url", SslUrl);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteStringValue("url", Url);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
