// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Netlify.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DeployEnvironmentVariable_scopes
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "builds")]
        #pragma warning disable CS1591
        Builds,
        #pragma warning restore CS1591
        [EnumMember(Value = "functions")]
        #pragma warning disable CS1591
        Functions,
        #pragma warning restore CS1591
        [EnumMember(Value = "runtime")]
        #pragma warning disable CS1591
        Runtime,
        #pragma warning restore CS1591
        [EnumMember(Value = "post-processing")]
        #pragma warning disable CS1591
        PostProcessing,
        #pragma warning restore CS1591
    }
}
