// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Netlify.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DevServerHookSetupType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "new_dev_server")]
        #pragma warning disable CS1591
        NewDevServer,
        #pragma warning restore CS1591
        [EnumMember(Value = "content_refresh")]
        #pragma warning disable CS1591
        ContentRefresh,
        #pragma warning restore CS1591
    }
}
