// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Netlify.OpenApiClient.Models
{
    /// <summary>
    /// Environment variable model definition
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EnvVar : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Secret values are only readable by code running on Netlify&apos;s systems. With secrets, only the local development context values are readable from the UI, API, and CLI. By default, environment variable values are not secret.</summary>
        public bool? IsSecret { get; set; }
        /// <summary>The environment variable key, like ALGOLIA_ID (case-sensitive)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The scopes that this environment variable is set to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Netlify.OpenApiClient.Models.EnvVar_scopes?>? Scopes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Netlify.OpenApiClient.Models.EnvVar_scopes?> Scopes { get; set; }
#endif
        /// <summary>The timestamp of when the value was last updated</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The updated_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Netlify.OpenApiClient.Models.EnvVarUser? UpdatedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Netlify.OpenApiClient.Models.EnvVarUser UpdatedBy { get; set; }
#endif
        /// <summary>An array of Value objects containing values and metadata</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Netlify.OpenApiClient.Models.EnvVarValue>? Values { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Netlify.OpenApiClient.Models.EnvVarValue> Values { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Models.EnvVar"/> and sets the default values.
        /// </summary>
        public EnvVar()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Models.EnvVar"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Netlify.OpenApiClient.Models.EnvVar CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Netlify.OpenApiClient.Models.EnvVar();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "is_secret", n => { IsSecret = n.GetBoolValue(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "scopes", n => { Scopes = n.GetCollectionOfEnumValues<global::Soenneker.Netlify.OpenApiClient.Models.EnvVar_scopes>()?.AsList(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "updated_by", n => { UpdatedBy = n.GetObjectValue<global::Soenneker.Netlify.OpenApiClient.Models.EnvVarUser>(global::Soenneker.Netlify.OpenApiClient.Models.EnvVarUser.CreateFromDiscriminatorValue); } },
                { "values", n => { Values = n.GetCollectionOfObjectValues<global::Soenneker.Netlify.OpenApiClient.Models.EnvVarValue>(global::Soenneker.Netlify.OpenApiClient.Models.EnvVarValue.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("is_secret", IsSecret);
            writer.WriteStringValue("key", Key);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Netlify.OpenApiClient.Models.EnvVar_scopes>("scopes", Scopes);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteObjectValue<global::Soenneker.Netlify.OpenApiClient.Models.EnvVarUser>("updated_by", UpdatedBy);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Netlify.OpenApiClient.Models.EnvVarValue>("values", Values);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
