// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Netlify.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSiteDatabaseBranchRoleParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "netlifydb_owner")]
        #pragma warning disable CS1591
        NetlifydbOwner,
        #pragma warning restore CS1591
        [EnumMember(Value = "netlifydb_readonly")]
        #pragma warning disable CS1591
        NetlifydbReadonly,
        #pragma warning restore CS1591
    }
}
