// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Netlify.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ServiceInstance : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The auth_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthUrl { get; set; }
#nullable restore
#else
        public string AuthUrl { get; set; }
#endif
        /// <summary>The config property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_config? Config { get; set; }
#nullable restore
#else
        public global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_config Config { get; set; }
#endif
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The env property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_env? Env { get; set; }
#nullable restore
#else
        public global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_env Env { get; set; }
#endif
        /// <summary>The external_attributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_external_attributes? ExternalAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_external_attributes ExternalAttributes { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The service_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceName { get; set; }
#nullable restore
#else
        public string ServiceName { get; set; }
#endif
        /// <summary>The service_path property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServicePath { get; set; }
#nullable restore
#else
        public string ServicePath { get; set; }
#endif
        /// <summary>The service_slug property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceSlug { get; set; }
#nullable restore
#else
        public string ServiceSlug { get; set; }
#endif
        /// <summary>The snippets property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_snippets>? Snippets { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_snippets> Snippets { get; set; }
#endif
        /// <summary>The updated_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance"/> and sets the default values.
        /// </summary>
        public ServiceInstance()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "auth_url", n => { AuthUrl = n.GetStringValue(); } },
                { "config", n => { Config = n.GetObjectValue<global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_config>(global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_config.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "env", n => { Env = n.GetObjectValue<global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_env>(global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_env.CreateFromDiscriminatorValue); } },
                { "external_attributes", n => { ExternalAttributes = n.GetObjectValue<global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_external_attributes>(global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_external_attributes.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "service_name", n => { ServiceName = n.GetStringValue(); } },
                { "service_path", n => { ServicePath = n.GetStringValue(); } },
                { "service_slug", n => { ServiceSlug = n.GetStringValue(); } },
                { "snippets", n => { Snippets = n.GetCollectionOfObjectValues<global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_snippets>(global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_snippets.CreateFromDiscriminatorValue)?.AsList(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("auth_url", AuthUrl);
            writer.WriteObjectValue<global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_config>("config", Config);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_env>("env", Env);
            writer.WriteObjectValue<global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_external_attributes>("external_attributes", ExternalAttributes);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("service_name", ServiceName);
            writer.WriteStringValue("service_path", ServicePath);
            writer.WriteStringValue("service_slug", ServiceSlug);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Netlify.OpenApiClient.Models.ServiceInstance_snippets>("snippets", Snippets);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
