// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Netlify.OpenApiClient.Models;
using Soenneker.Netlify.OpenApiClient.Sites.Item.AiGateway;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Assets;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Build_hooks;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Builds;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Database;
using Soenneker.Netlify.OpenApiClient.Sites.Item.DeployedBranches;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Deploys;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Dev_server_hooks;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Dev_servers;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Disable;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Dns;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Enable;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Files;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Forms;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Functions;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Metadata;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Plugin_runs;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Plugins;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Rollback;
using Soenneker.Netlify.OpenApiClient.Sites.Item.ServiceInstances;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Services;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Snippets;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Ssl;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Submissions;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Traffic_splits;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Unlink_repo;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Netlify.OpenApiClient.Sites.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \sites\{site_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSite_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The aiGateway property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.AiGateway.AiGatewayRequestBuilder AiGateway
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.AiGateway.AiGatewayRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The assets property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Assets.AssetsRequestBuilder Assets
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Assets.AssetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The build_hooks property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Build_hooks.Build_hooksRequestBuilder Build_hooks
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Build_hooks.Build_hooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The builds property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Builds.BuildsRequestBuilder Builds
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Builds.BuildsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The database property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.DatabaseRequestBuilder Database
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.DatabaseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deployedBranches property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.DeployedBranches.DeployedBranchesRequestBuilder DeployedBranches
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.DeployedBranches.DeployedBranchesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deploys property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Deploys.DeploysRequestBuilder Deploys
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Deploys.DeploysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dev_server_hooks property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Dev_server_hooks.Dev_server_hooksRequestBuilder Dev_server_hooks
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Dev_server_hooks.Dev_server_hooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dev_servers property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Dev_servers.Dev_serversRequestBuilder Dev_servers
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Dev_servers.Dev_serversRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The disable property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Disable.DisableRequestBuilder Disable
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Disable.DisableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dns property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Dns.DnsRequestBuilder Dns
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Dns.DnsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enable property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Enable.EnableRequestBuilder Enable
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Enable.EnableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The files property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Files.FilesRequestBuilder Files
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The forms property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Forms.FormsRequestBuilder Forms
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Forms.FormsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The functions property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Functions.FunctionsRequestBuilder Functions
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Functions.FunctionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metadata property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Metadata.MetadataRequestBuilder Metadata
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Metadata.MetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The plugin_runs property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Plugin_runs.Plugin_runsRequestBuilder Plugin_runs
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Plugin_runs.Plugin_runsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The plugins property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Plugins.PluginsRequestBuilder Plugins
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Plugins.PluginsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rollback property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Rollback.RollbackRequestBuilder Rollback
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Rollback.RollbackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The serviceInstances property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.ServiceInstances.ServiceInstancesRequestBuilder ServiceInstances
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.ServiceInstances.ServiceInstancesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The services property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Services.ServicesRequestBuilder Services
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Services.ServicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The snippets property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Snippets.SnippetsRequestBuilder Snippets
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Snippets.SnippetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ssl property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Ssl.SslRequestBuilder Ssl
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Ssl.SslRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The submissions property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Submissions.SubmissionsRequestBuilder Submissions
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Submissions.SubmissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The traffic_splits property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Traffic_splits.Traffic_splitsRequestBuilder Traffic_splits
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Traffic_splits.Traffic_splitsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unlink_repo property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Unlink_repo.Unlink_repoRequestBuilder Unlink_repo
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Unlink_repo.Unlink_repoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Sites.Item.WithSite_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSite_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{site_id}{?feature_flags*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Sites.Item.WithSite_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSite_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{site_id}{?feature_flags*}", rawUrl)
        {
        }
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Netlify.OpenApiClient.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Netlify.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// **Note:** Environment variable keys and values have moved from `build_settings.env` and `repo.env` to a new endpoint. Please use [getEnvVars](#tag/environmentVariables/operation/getEnvVars) to retrieve site environment variables.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Models.Site"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Netlify.OpenApiClient.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Netlify.OpenApiClient.Models.Site?> GetAsync(Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Sites.Item.WithSite_ItemRequestBuilder.WithSite_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Netlify.OpenApiClient.Models.Site> GetAsync(Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Sites.Item.WithSite_ItemRequestBuilder.WithSite_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Netlify.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Netlify.OpenApiClient.Models.Site>(requestInfo, global::Soenneker.Netlify.OpenApiClient.Models.Site.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// **Note:** Environment variable keys and values have moved from `build_settings.env` and `repo.env` to a new endpoint. Please use [updateEnvVar](#tag/environmentVariables/operation/updateEnvVar) to update a site&apos;s environment variables.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Models.Site"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Netlify.OpenApiClient.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Netlify.OpenApiClient.Models.Site?> PatchAsync(global::Soenneker.Netlify.OpenApiClient.Models.SiteSetup body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Netlify.OpenApiClient.Models.Site> PatchAsync(global::Soenneker.Netlify.OpenApiClient.Models.SiteSetup body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Netlify.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Netlify.OpenApiClient.Models.Site>(requestInfo, global::Soenneker.Netlify.OpenApiClient.Models.Site.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// **Note:** Environment variable keys and values have moved from `build_settings.env` and `repo.env` to a new endpoint. Please use [getEnvVars](#tag/environmentVariables/operation/getEnvVars) to retrieve site environment variables.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Sites.Item.WithSite_ItemRequestBuilder.WithSite_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Sites.Item.WithSite_ItemRequestBuilder.WithSite_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// **Note:** Environment variable keys and values have moved from `build_settings.env` and `repo.env` to a new endpoint. Please use [updateEnvVar](#tag/environmentVariables/operation/updateEnvVar) to update a site&apos;s environment variables.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Netlify.OpenApiClient.Models.SiteSetup body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Netlify.OpenApiClient.Models.SiteSetup body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Sites.Item.WithSite_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.WithSite_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Netlify.OpenApiClient.Sites.Item.WithSite_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// **Note:** Environment variable keys and values have moved from `build_settings.env` and `repo.env` to a new endpoint. Please use [getEnvVars](#tag/environmentVariables/operation/getEnvVars) to retrieve site environment variables.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithSite_ItemRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("feature_flags")]
            public string? FeatureFlags { get; set; }
#nullable restore
#else
            [QueryParameter("feature_flags")]
            public string FeatureFlags { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
