// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Netlify.OpenApiClient.Models;
using Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Migrations.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Migrations
{
    /// <summary>
    /// Builds and executes requests for operations under \sites\{site_id}\database\migrations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MigrationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Netlify.OpenApiClient.sites.item.database.migrations.item collection</summary>
        /// <param name="position">The deploy ID to run migrations for</param>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Migrations.Item.Deploy_ItemRequestBuilder"/></returns>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Migrations.Item.Deploy_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("deploy_%2Did", position);
                return new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Migrations.Item.Deploy_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Migrations.MigrationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MigrationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{site_id}/database/migrations{?branch*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Migrations.MigrationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MigrationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{site_id}/database/migrations{?branch*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns the list of migrations available for the specified branch, indicating which ones have been applied to the database.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Models.ListDatabaseMigrationsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Netlify.OpenApiClient.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Netlify.OpenApiClient.Models.ListDatabaseMigrationsResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Migrations.MigrationsRequestBuilder.MigrationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Netlify.OpenApiClient.Models.ListDatabaseMigrationsResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Migrations.MigrationsRequestBuilder.MigrationsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Netlify.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Netlify.OpenApiClient.Models.ListDatabaseMigrationsResponse>(requestInfo, global::Soenneker.Netlify.OpenApiClient.Models.ListDatabaseMigrationsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the list of migrations available for the specified branch, indicating which ones have been applied to the database.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Migrations.MigrationsRequestBuilder.MigrationsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Migrations.MigrationsRequestBuilder.MigrationsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Migrations.MigrationsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Migrations.MigrationsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Netlify.OpenApiClient.Sites.Item.Database.Migrations.MigrationsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns the list of migrations available for the specified branch, indicating which ones have been applied to the database.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MigrationsRequestBuilderGetQueryParameters 
        {
            /// <summary>The branch ID to list migrations for. Defaults to &quot;production&quot; if not specified.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("branch")]
            public string? Branch { get; set; }
#nullable restore
#else
            [QueryParameter("branch")]
            public string Branch { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
