// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Netlify.OpenApiClient.Accounts.Item.AiGateway.Token;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Netlify.OpenApiClient.Accounts.Item.AiGateway
{
    /// <summary>
    /// Builds and executes requests for operations under \accounts\{account_id}\ai-gateway
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AiGatewayRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The token property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Accounts.Item.AiGateway.Token.TokenRequestBuilder Token
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Accounts.Item.AiGateway.Token.TokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Accounts.Item.AiGateway.AiGatewayRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AiGatewayRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts/{account_id}/ai-gateway", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Accounts.Item.AiGateway.AiGatewayRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AiGatewayRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts/{account_id}/ai-gateway", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
