// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Netlify.OpenApiClient.Item.Builds;
using Soenneker.Netlify.OpenApiClient.Item.Members;
using Soenneker.Netlify.OpenApiClient.Item.Sites;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Netlify.OpenApiClient.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \{account_-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Account_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The builds property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Item.Builds.BuildsRequestBuilder Builds
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Item.Builds.BuildsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The members property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Item.Members.MembersRequestBuilder Members
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Item.Members.MembersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sites property</summary>
        public global::Soenneker.Netlify.OpenApiClient.Item.Sites.SitesRequestBuilder Sites
        {
            get => new global::Soenneker.Netlify.OpenApiClient.Item.Sites.SitesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Item.Account_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Account_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{account_%2Did}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Item.Account_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Account_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{account_%2Did}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
