// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.Item;
using Soenneker.Netlify.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Netlify.OpenApiClient.Accounts.Item.Env
{
    /// <summary>
    /// Builds and executes requests for operations under \accounts\{account_id}\env
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EnvRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Netlify.OpenApiClient.accounts.item.env.item collection</summary>
        /// <param name="position">The environment variable key (case-sensitive)</param>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.Item.WithKeyItemRequestBuilder"/></returns>
        public global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.Item.WithKeyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("key", position);
                return new global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.Item.WithKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.EnvRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EnvRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts/{account_id}/env{?context_name*,scope*,site_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.EnvRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EnvRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts/{account_id}/env{?context_name*,scope*,site_id*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns all environment variables for an account or site. An account corresponds to a team in the Netlify UI.
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Netlify.OpenApiClient.Models.EnvVar&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Netlify.OpenApiClient.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Netlify.OpenApiClient.Models.EnvVar>?> GetAsync(Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.EnvRequestBuilder.EnvRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Netlify.OpenApiClient.Models.EnvVar>> GetAsync(Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.EnvRequestBuilder.EnvRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Netlify.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Netlify.OpenApiClient.Models.EnvVar>(requestInfo, global::Soenneker.Netlify.OpenApiClient.Models.EnvVar.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Creates new environment variables. Granular scopes are available on Pro plans and above.
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Netlify.OpenApiClient.Models.EnvVar&gt;</returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Netlify.OpenApiClient.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Netlify.OpenApiClient.Models.EnvVar>?> PostAsync(List<global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.Env> body, Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.EnvRequestBuilder.EnvRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Netlify.OpenApiClient.Models.EnvVar>> PostAsync(List<global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.Env> body, Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.EnvRequestBuilder.EnvRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Netlify.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Netlify.OpenApiClient.Models.EnvVar>(requestInfo, global::Soenneker.Netlify.OpenApiClient.Models.EnvVar.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Returns all environment variables for an account or site. An account corresponds to a team in the Netlify UI.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.EnvRequestBuilder.EnvRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.EnvRequestBuilder.EnvRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates new environment variables. Granular scopes are available on Pro plans and above.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(List<global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.Env> body, Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.EnvRequestBuilder.EnvRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(List<global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.Env> body, Action<RequestConfiguration<global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.EnvRequestBuilder.EnvRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.EnvRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.EnvRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.EnvRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns all environment variables for an account or site. An account corresponds to a team in the Netlify UI.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EnvRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter by deploy context</summary>
            [QueryParameter("context_name")]
            public global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.GetContext_nameQueryParameterType? ContextName { get; set; }
            /// <summary>Filter by scope</summary>
            [QueryParameter("scope")]
            public global::Soenneker.Netlify.OpenApiClient.Accounts.Item.Env.GetScopeQueryParameterType? Scope { get; set; }
            /// <summary>If specified, only return environment variables set on this site</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("site_id")]
            public string? SiteId { get; set; }
#nullable restore
#else
            [QueryParameter("site_id")]
            public string SiteId { get; set; }
#endif
        }
        /// <summary>
        /// Creates new environment variables. Granular scopes are available on Pro plans and above.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EnvRequestBuilderPostQueryParameters 
        {
            /// <summary>If provided, create an environment variable on the site level, not the account level</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("site_id")]
            public string? SiteId { get; set; }
#nullable restore
#else
            [QueryParameter("site_id")]
            public string SiteId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
