// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Netlify.OpenApiClient.Accounts.Item.Env
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetContext_nameQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
        [EnumMember(Value = "dev")]
        #pragma warning disable CS1591
        Dev,
        #pragma warning restore CS1591
        [EnumMember(Value = "dev-server")]
        #pragma warning disable CS1591
        DevServer,
        #pragma warning restore CS1591
        [EnumMember(Value = "branch-deploy")]
        #pragma warning disable CS1591
        BranchDeploy,
        #pragma warning restore CS1591
        [EnumMember(Value = "deploy-preview")]
        #pragma warning disable CS1591
        DeployPreview,
        #pragma warning restore CS1591
        [EnumMember(Value = "production")]
        #pragma warning disable CS1591
        Production,
        #pragma warning restore CS1591
    }
}
